<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Ticket;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNumberVisitors($dateVisit)
    {
        return $this->createQueryBuilder('t')
            ->andWhere('t.dateVisit = :dateVisit')
            ->setParameter('dateVisit', $dateVisit)
            ->select('SUM(t.nbVisitors)')
            ->getQuery()
            ->getSingleScalarResult();

            }

}
